name: mmdutil
version: "2.1"
summary: Markdown conversion utility.
description: |
  mmdutil is a simple markdown conversion utility that generates HTML or man
  page source from markdown.  mmdutil supports most of the CommonMark syntax
  as well as the metadata, "@" link, table, and task list markdown extensions.

confinement: strict

grade: stable

icon: mmd-128.png

apps:
    mmdutil:
        command: bin/mmdutil
        plugs: [home]

parts:
    main:
        plugin: make
        source: .
        make-install-var: prefix
